name: Build Expo App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  EXPO_SDK_VERSION: "50.0.4"
  EAS_CLI_VERSION: "0.55.0"
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} # تم نقل EXPO_TOKEN إلى مستوى الوظيفة

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo CLI and EAS CLI
        run: npm install -g expo-cli@latest eas-cli@${{ env.EAS_CLI_VERSION }}

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Delete node_modules
        run: rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build Android app (Development)
        run: eas build --platform android --profile development --non-interactive

      - name: Upload Development Android Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-dev-app.apk
          path: android/app/build/outputs/apk/development/debug/app-development-debug.apk

      - name: Build Android app (Production)
        run: eas build --platform android --profile production --non-interactive

      - name: Upload Production Android Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-production-app.aab
          path: android/app/build/outputs/bundle/release/app-release.aab
